steps:
  - label: "test"
    commands:
      - make -C web test
    plugins:¬
      - docker#v3.0.1:
          always-pull: true
          image: replicated/gitops-builder:buildkite
          workdir: /repo
